### ISSUE TITLE
기존 한글패치-자나타 누락데이터 분석

### ISSUE THREAD

**Issue by Whya5448** [Whya5448/zariel#4]

**Comment by harion01** [comment]
자타나 파일/ 엘온 파일 매칭을 위한 분석 시작

**Comment by harion01** [comment]
자동한글화 - 자타나 Po에서 한글화 안된걸 google translate api로 자동 번역하는 api 개발

**Comment by Whya5448** [comment]
en.lang에서 데이터 직접 뽑아내 새로운 프로젝트 오픈하였으므로 해결
