### ISSUE TITLE
자나타 ESO-Book에서 Handbills~/Houses~ 문서 번역이 적용 안됨

### ISSUE THREAD

**Issue by Nickelpie** [Whya5448/zariel#9]
Handbills,_Posters,_and_Decrees 문서랑 Houses,_Shops,_and_Trade 문서에 있는 번역 내용이 게임에 적용이 안됩니다. 언제부터인지는 모르겠지만 기존 번역 내용이 다 날아가버렸는데, 혹시 이거랑 관련있는건 아닌가요? 날아간 뒤에 다시 번역해 넣었는데 업데이터를 써도 번역 내용이 인게임에 안나옵니다.

**Comment by Whya5448** [comment]
자나타 버그, 문서명에 ',' 들어갈 경우 po 다운로드 시 번역 데이터가 없음. 
문서명 변경으로 처리 완료
